# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint4_3k-basic_d1.json --configfile configs/experiments/leave_task_train_t4.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --cross_task_options_prob 0.0 --none_of_above_prob 0.0 --instruction_option_size -1 --instruction_binary_size -1 
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint4_3k-nc_noibio_d1.json --configfile configs/experiments/leave_task_train_t4.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --cross_task_options_prob 0.1 --none_of_above_prob 0.1 --instruction_option_size -1 --instruction_binary_size -1
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint4_3k-nc_noio_d1.json --configfile configs/experiments/leave_task_train_t4.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --cross_task_options_prob 0.1 --none_of_above_prob 0.1 --instruction_option_size -1 
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint4_3k-bonc_d1.json --configfile configs/experiments/leave_task_train_t4.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --cross_task_options_prob 0.1 --none_of_above_prob 0.1 --instruction_option_size 200 
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint4_3k-boc_nonota_d1.json --configfile configs/experiments/leave_task_train_t4.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --cross_task_options_prob 0.1 --none_of_above_prob 0.0 --instruction_option_size 200  
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint4_3k-bon_noc_d1.json --configfile configs/experiments/leave_task_train_t4.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --cross_task_options_prob 0.0 --none_of_above_prob 0.1 --instruction_option_size 200  

# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint5_5k-basic_d1.json --configfile configs/experiments/leave_task_train_t5.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --cross_task_options_prob 0.0 --none_of_above_prob 0.0 --instruction_option_size -1 --instruction_binary_size -1 
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint5_5k-n_noibio_d1.json --configfile configs/experiments/leave_task_train_t5.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --cross_task_options_prob 0.0 --none_of_above_prob 0.05 --instruction_option_size -1 --instruction_binary_size -1
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint5_5k-bo_nonota_d1.json --configfile configs/experiments/leave_task_train_t5.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --cross_task_options_prob 0.0 --none_of_above_prob 0.0 --instruction_option_size 200  --instruction_binary_size 1000
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint5_5k-bon_noc_d1.json --configfile configs/experiments/leave_task_train_t5.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --cross_task_options_prob 0.0 --none_of_above_prob 0.1 --instruction_option_size 200  --instruction_binary_size 1000
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint5_5k-bonc_d1.json --configfile configs/experiments/leave_task_train_t5.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --cross_task_options_prob 0.1 --none_of_above_prob 0.05 --instruction_option_size 200 --instruction_binary_size 1000
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint5_5k-bon_noc_d2morebo.json --configfile configs/experiments/leave_task_train_t5.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --cross_task_options_prob 0.0 --none_of_above_prob 0.1 --instruction_option_size 500  --instruction_binary_size 5000
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/testdata_debug_leavetasktraint5.json --configfile configs/experiments/leave_task_train_t5.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 500 --cross_task_options_prob 0.0 --none_of_above_prob 0.0 --instruction_option_size -1 --instruction_binary_size -1 


# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint6_5k-basic_d1.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --none_of_above_prob 0.0 --instruction_option_size -1 --instruction_binary_size -1 
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint6_5k-n_noibio_d1.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --none_of_above_prob 0.05 --instruction_option_size -1 --instruction_binary_size -1
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint6_5k-bo_nonota_d1.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --none_of_above_prob 0.0 --instruction_option_size 200  --instruction_binary_size 1000
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint6_5k-bon_d1.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --none_of_above_prob 0.05 --instruction_option_size 200 --instruction_binary_size 1000
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint6_5k-bon_d2morebo.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --none_of_above_prob 0.05 --instruction_option_size 500  --instruction_binary_size 5000
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_debug_leavetasktraint6_5k-bon_d2moren.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 5000 --none_of_above_prob 0.2 --instruction_option_size 200  --instruction_binary_size 1000
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/testdata_debug_leavetasktestt6.json --configfile configs/experiments/leave_task_test_t6.json --tasksfiles_folder tasks_files/tasks_files-testconfig1/  --max_task_size 500 --cross_task_options_prob 0.0 --none_of_above_prob 0.0 --instruction_option_size -1 --instruction_binary_size -1 

#ablation vary task
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/ablation_tasknumvary/traindata_lt6_3k-numt5_d1.json --configfile configs/ablation_tasknumvary/leave_task_train_t6_numt5.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --none_of_above_prob 0.1 --instruction_option_size 50 --instruction_binary_size 200
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/ablation_tasknumvary/traindata_lt6_3k-numt10_d1.json --configfile configs/ablation_tasknumvary/leave_task_train_t6_numt10.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --none_of_above_prob 0.1 --instruction_option_size 80 --instruction_binary_size 400
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/ablation_tasknumvary/traindata_lt6_3k-numt20_d1.json --configfile configs/ablation_tasknumvary/leave_task_train_t6_numt20.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --none_of_above_prob 0.1 --instruction_option_size 100 --instruction_binary_size 600
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/ablation_tasknumvary/traindata_lt6_3k-numt30_d1.json --configfile configs/ablation_tasknumvary/leave_task_train_t6_numt30.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --none_of_above_prob 0.1 --instruction_option_size 150 --instruction_binary_size 800
# python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/ablation_tasknumvary/traindata_lt6_3k-numt40_d1.json --configfile configs/ablation_tasknumvary/leave_task_train_t6_numt40.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --none_of_above_prob 0.1 --instruction_option_size 200 --instruction_binary_size 1000
python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/ablation_tasknumvary/traindata_lt6_3k-numt25_d1.json --configfile configs/ablation_tasknumvary/leave_task_train_t6_numt25.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --none_of_above_prob 0.1 --instruction_option_size 150 --instruction_binary_size 800
python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/ablation_tasknumvary/traindata_lt6_3k-numt35_d1.json --configfile configs/ablation_tasknumvary/leave_task_train_t6_numt35.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --none_of_above_prob 0.1 --instruction_option_size 200 --instruction_binary_size 1000


python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_lt6_1k-bon_d1.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 1000 --none_of_above_prob 0.05 --instruction_option_size 200 --instruction_binary_size 1000
python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_lt6_2k-bon_d1.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 2000 --none_of_above_prob 0.05 --instruction_option_size 200 --instruction_binary_size 1000
python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_lt6_3k-bon_d1.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 3000 --none_of_above_prob 0.05 --instruction_option_size 200 --instruction_binary_size 1000
python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_lt6_4k-bon_d1.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 4000 --none_of_above_prob 0.05 --instruction_option_size 200 --instruction_binary_size 1000
python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_lt6_6k-bon_d1.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 6000 --none_of_above_prob 0.05 --instruction_option_size 200 --instruction_binary_size 1000
python -m scripts.create_data_text2text --outputfile scripts/text2textfiles/leavetasks/traindata_lt6_7k-bon_d1.json --configfile configs/experiments/leave_task_train_t6.json --tasksfiles_folder tasks_files/tasks_files-full-trainconfig1/  --max_task_size 7000 --none_of_above_prob 0.05 --instruction_option_size 200 --instruction_binary_size 1000


# --outputfile scripts/text2textfiles/t2t_generate_test.json \
#  --configfile configs/t2t_generate_test.json \
#  --tasksfiles_folder tasks_files/tasks_files-c10k-train/

   
